### ISSUE TITLE
Large images overflow post container

### ISSUE THREAD

**Issue by ghost** [geschke/hugo-tikva#10]
Not sure if this project is still active, but I saw a potential bug and wanted to bring it up. Large images in posts seem to overflow their container. I think there needs to be a max-width:100% added somewhere, but I'm not sure where.

Steps to reproduce:
1. Create new site, add Tikva theme, copy exampleSite files and example config.toml.
2. In one of the example markdown posts, add an image, ex. `![testimage](/img/testimage.jpg)` or `![testimage](testimage.jpg)` if it's in a post bundle. The image I'm using is 4032x3024.
3. Start hugo server, navigate to post, post image will be overflowing the post container.

![image](https://user-images.githubusercontent.com/10841438/218873857-f1ddd79c-6d20-41ea-953f-382dc89b69cb.png)

If I do an inspect element on the image, I can add max-width:100% and it fixes it. I might be missing something dumb but this feels like a bug.

**Comment by geschke** [comment]
Hello!

Thanks for reporting this issue! To be honest, the theme is quite outdated, but still active. I wouldn't recommend using it for new sites because the underlying libraries like Bootstrap, jQuery and so on are out of date as well. 

However, I will implement a solution that comes from another Hugo template with the same MIT license and is based on Hugo's image processing features. Please give me some time to release the new version, because I want to make the new behavior optional to keep backward compatibility. 

Kind regards,
   Ralf

**Comment by geschke** [comment]
The updated version has just been published.

To enable the new behavior, add the following to your configuration file (for example, in config.toml):

```toml
[params.images]
    extendedRendering = true # backward compatible default setting is "false"; set to true to activate extended image rendering functions
```
