### ISSUE TITLE
Dont't load javascript with http when page is https

### ISSUE THREAD

**Issue by piratenpanda** [geschke/hugo-tikva#2]
I'm getting blocked javascript when running the theme on my homepage as firefox is blocking all http content automatically. Is there an easy way to change this?

**Comment by piratenpanda** [comment]
Base URL is properly set to the https version

**Comment by piratenpanda** [comment]
Sorry for spamming. I also see localhost and port everywhere where it says .Site.BaseURL  in the templates

**Comment by geschke** [comment]
Hello! 

Thanks for reporting, but unfortunately I could not reproduce the problem. Does it still not work? I'm using the theme on my site https://www.geschke.net - and as you can see (have a look at the source code), the CSS and JavaScript files are also loaded via https as expected. 

If you see "localhost" there, I assume that you're using the hugo server started with default options on the command line? In that case please have a look at https://gohugo.io/getting-started/usage/ -> "Deploy your website" and similar chapters. 

Otherwise please send me the URL and the config file, so I can try to check in on your site. If you don't want to publish this information here, just drop me a mail or use the feedback formular on my site. 

Kind regards,
   Ralf

**Comment by geschke** [comment]
No feedback since six months, so I guess the issue can be closed.
