### ISSUE TITLE
Newlines in subtitles

### ISSUE THREAD

**Issue by thanh-hai-tran** [geschke/hugo-tikva#4]
Hi Gescheke,

I am learning hugo with your theme Tikva. I want to have a break line (or new line) in the subtitle. I haved rewritten the given config.toml as following

```
[params]
    subtitle = "first line \n second line "
```

However, I received an error 
```
unmarshal failed: Near line 28 (last key parsed 'params.subtitle'): strings cannot contain newlines
```

Do you know how to fix it? Thank you very much!

Best regards,
Thanh Hai

**Comment by geschke** [comment]
Hello Thanh Hai!

Please have a look at https://discourse.gohugo.io/t/linebreaks-in-front-matter-using-academic-theme/9809 . Maybe this could be a solution for your problem. 

To customize the theme, copy the necessary layout file into your project's layout folder. I guess that you're using the default header ( style = "header" in params.navbar), because with style="fixed-top" the subtitle will not be displayed.
So you have to copy the partial /themes/hugo-tikva/layouts/partials/header_default.html into <your-project>/layouts/partials/ . 
In this file search for the subtitle output and replace {{ .Site.Params.Subtitle }} with {{ .Site.Params.Subtitle | safeHTML }} . 

Hope this helps!

Kind regards,
   Ralf

**Comment by thanh-hai-tran** [comment]
Thanks a lot, Geschke! The link and your comment are very helpful. I have fixed it by applying what you mentioned.
