### ISSUE TITLE
Missing options for display of headers on home page

### ISSUE THREAD

**Issue by scottpedia** [geschke/hugo-tikva#9]
I loaded the same configuration as the example site. But I noticed it is still different from the demo site. On the demo site, there is only one title on the homepage, which is located on the header image on the top. But on my local site with the example configuration, there are two repetitive header titles, one above the header image on the top, and another one below the navigation bar. I could not find the option for that in the theme configuration also. 

There are also some other differences, like the "Read more" button for every post, which is not found on my local site. Are there configurable options for these traits?

**Comment by geschke** [comment]
What happens if you use the content of the exampleSite folder and run hugo? It seems that the content in your screenshot is not the index page. Please show the markdown source of your page, does an in. Does it have a "title" row in the header? How about your folder structure, does an _index.md file exist? Are there files in the "posts" folder and also an _index.md file?

**Comment by scottpedia** [comment]
I think that I know where the problems are. But still thank you!

By the way, I tried to run the example site in the repo. And it came out like this:

<img width="1238" alt="Screen Shot 2020-12-20 at 11 06 21" src="https://user-images.githubusercontent.com/60531983/102717941-65d57800-42b3-11eb-8d93-1243f9801095.png">

still being different from the demo site.
